plakalar = {"KEREM OZBAL": "34 TO 2015", "ALPER YUKSEL" : "16 NOG 95", "RAGIP DUNDAR" : "06 HBT 11",
                        "ADNAN MUTU": "06 ANK 06", "ISMAIL GUNDUZ" : "31 A 0001", "TEOMAN ARSLAN" : "17 CNK 17",
                        "MERVE ARIK": "34 BUF 80", "TUBAĞ SEZGİN": "16 UCB 25", "ALPEREN ÇAKICI" : "34 TS 061",
                        "ŞEVVAL YILDIZ": "34 MEH 52"}
cezalar = {"Hurdaya çıkarılan aracın işlemlerini yapmamak":427,
                   "Sattığı aracı ilgili kurumlara bildirmemek":3340,
                   "İhaleden alınan araçlarda gerekli bilgileri vermemek": 427,
                   "Tescil plaklasız araç kullanmak": 1823,
                   "Hurda belgeli araç kullanmak": 3674,
                   "Araçta ruhsat bulundurmamak": 166,
                   "Plakayı yanlış yere takmak": 166,
                   "App plaka kullanmak": 750,
                   "İzin verilen sürede uygun plaka takmamak": 1536,
                   "Araç cinsine göre belirlenen sayıda plaka takmamak": 750,
                   "Plaka üzerinde değişiklik yapmak": 750,
                   "Plakasız araç kullanmak": 3093,
                   "Başka aracın plakasını kullanmak": 9107,
                   "Sahte plaka takmak": 9107,
                   "Geçici tescil işlemleri yapmamak": 427,
                   "Araçda bulundurulması gereken donanımları bulundurmamak": 196,
                   "Mevzuata aykırı ışık kullanmak": 1823,
                   "Araç üzerinde renk değişikliği veya reklam yapıştırmak": 196,
                   "Gerekli ışık donanımı çalışmayan araç kullanmak": 196,
                   "Abartı egzoz veya cam filmi kullanmak": 427,
                   "Araç cinsinde bulundurulması zorunlu gereçleri bulundurmamak": 196}
