from PyQt5 import QtCore, QtGui, QtWidgets # Arayüz için gerekli kütüphaneleri aktif ettik.++


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(510, 624)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rozet polis.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog.setWindowIcon(icon)
        dialog.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0.591, x2:0.483373, y2:0.602, stop:0 rgba(182, 214, 226, 245), stop:1 rgba(255, 255, 255, 255));")
        dialog.setSizeGripEnabled(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 491, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 120, 151, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("png-transparent-computer-icons-camera-camera-photography-rectangle-camera-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 29, 491, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_2)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 310, 491, 130))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setRange(0,1000)
        self.spinBox_2.setRange(0,1000)
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 440, 491, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "CEZA-ÜL SİSTEM-ÜL TESPİT(CST)"))
        dialog.setToolTip(_translate("dialog", "<html><head/><body><p>file:///C:/Users/gomer/OneDrive/Masaüstü/rozet polis.png</p></body></html>"))
        dialog.setWhatsThis(_translate("dialog", "<html><head/><body><p>cvbx</p></body></html>"))
        self.label_5.setText(_translate("dialog", "CEZA TİPİ SEÇİNİZ ;"))
        self.comboBox.setItemText(0, _translate("dialog", "ceza tipi seçiniz..."))
        self.comboBox.setItemText(1, _translate("dialog", "Hız sınırı aşımı"))
        self.comboBox.setItemText(2, _translate("dialog", "Hurdaya çıkarılan aracın işlemlerini yapmamak"))
        self.comboBox.setItemText(3, _translate("dialog", "Sattığı aracı ilgili kurumlara bildirmemek"))
        self.comboBox.setItemText(4, _translate("dialog", "İhaleden alınan araçlarda gerekli bilgileri vermemek"))
        self.comboBox.setItemText(5, _translate("dialog", "Tescil plakasız araç kullanmak"))
        self.comboBox.setItemText(6, _translate("dialog", "Hurda belgeli araç kullanmak"))
        self.comboBox.setItemText(7, _translate("dialog", "Araçta ruhsat bulundurmamak"))
        self.comboBox.setItemText(8, _translate("dialog", "Plakayı yanlış yere takmak"))
        self.comboBox.setItemText(9, _translate("dialog", "App plaka kullanmak"))
        self.comboBox.setItemText(10, _translate("dialog", "İzin verilen sürede uygun plaka takmamak"))
        self.comboBox.setItemText(11, _translate("dialog", "Araç cinsine göre belirlenen sayıda plaka takmamak"))
        self.comboBox.setItemText(12, _translate("dialog", "Plaka üzerinde değişiklik yapmak"))
        self.comboBox.setItemText(13, _translate("dialog", "Plakasız araç kullanmak"))
        self.comboBox.setItemText(14, _translate("dialog", "Başka aracın plakasını kullanmak"))
        self.comboBox.setItemText(15, _translate("dialog", "Sahte plaka takmak"))
        self.comboBox.setItemText(16, _translate("dialog", "Geçici tescil işlemleri yapmamak"))
        self.comboBox.setItemText(17, _translate("dialog", "Araçda bulundurulması gereken donanımları bulundurmamak"))
        self.comboBox.setItemText(18, _translate("dialog", "Mevzuata aykırı ışık kullanmak"))
        self.comboBox.setItemText(19, _translate("dialog", "Araç üzerinde renk değişikliği veya reklam yapıştırmak"))
        self.comboBox.setItemText(20, _translate("dialog", "Gerekli ışık donanımı çalışmayan araç kullanmak"))
        self.comboBox.setItemText(21, _translate("dialog", "Abartı egzoz veya cam filmi kullanmak"))
        self.comboBox.setItemText(22, _translate("dialog", "Araç cinsinde bulundurulması zorunlu gereçleri bulundurmamak"))
        self.pushButton.setText(_translate("dialog", "KAMERA AÇ"))
        self.label.setText(_translate("dialog", " LÜTFEN TARİH SEÇİNİZ ;"))
        self.label_3.setText(_translate("dialog", "HIZ SINIRI ;"))
        self.label_2.setText(_translate("dialog", "UYGULANAN HIZ ;"))
        self.pushButton_2.setText(_translate("dialog", "ONAYLA")) 
